Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace DOCUMENTMANAGER.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult AboutUs()
        {
            return View();
        }
    }
}

Controllers/DashboardController.cs
using DOCUMENTMANAGER.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using System.IO.Compression;
using System.Text;

namespace DOCUMENTMANAGER.Controllers
{
    public class DashboardController : Controller
    {

        private readonly DOCMANAGERContext _context;
        private readonly IFileProvider _fileProvider;
        private readonly IWebHostEnvironment _hostingEnvironment;
        
        public DashboardController(IFileProvider fileProvider, DOCMANAGERContext context, IWebHostEnvironment hostingEnvironment)
        {
            _fileProvider = fileProvider;
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Index()
        {
            var documents = GetDocuments();
            return View(documents);
        }

        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile profilePhoto, IFormFile aadharCard, IFormFile panCard, IFormFile voterId, IFormFile marksheet)
        {
           long? UserId = Convert.ToInt64(HttpContext.Session.GetString("User_Id"));
            // Your file upload logic for each document type
            if (profilePhoto != null)
            {
                if (profilePhoto.Length > 0)
                {
                    var fileName = Path.GetFileName(voterId.FileName);
                    var filePath = Path.Combine(_hostingEnvironment.WebRootPath, "Uploads", profilePhoto.FileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await profilePhoto.CopyToAsync(stream);
                    }


                    SaveDocumentToDatabase(fileName, filePath,UserId);
                }
            }

            if (aadharCard != null)
            {
                // Process Aadhar Card
                if (aadharCard.Length > 0)
                {
                    var fileName = Path.GetFileName(aadharCard.FileName);
                    var filePath = Path.Combine(_hostingEnvironment.WebRootPath, "Uploads", aadharCard.FileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await aadharCard.CopyToAsync(stream);

                    }

                    SaveDocumentToDatabase(fileName, filePath, UserId);
                }
            }

            if (panCard != null)
            {
                // Process Pan Card
                if (panCard.Length > 0)
                {
                    var fileName = Path.GetFileName(panCard.FileName);
                    var filePath = Path.Combine(_hostingEnvironment.WebRootPath, "Uploads", panCard.FileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await panCard.CopyToAsync(stream);

                    }

                    SaveDocumentToDatabase(fileName, filePath, UserId);
                }
            }

            if (voterId != null)
            {
                // Process Voter Id
                if (voterId.Length > 0)
                {
                    var fileName = Path.GetFileName(voterId.FileName);
                    var filePath = Path.Combine(_hostingEnvironment.WebRootPath, "Uploads", voterId.FileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await voterId.CopyToAsync(stream);

                    }

                    SaveDocumentToDatabase(fileName, filePath, UserId);
                }
            }

            if (marksheet != null)
            {
                // Process Marksheet
                 if (marksheet.Length > 0)
                {
                    var fileName = Path.GetFileName(marksheet.FileName);
                    var filePath = Path.Combine(_hostingEnvironment.WebRootPath, "Uploads", marksheet.FileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await marksheet.CopyToAsync(stream);

                    }

                    SaveDocumentToDatabase(fileName, filePath, UserId);
                }
            }

            // Redirect or return a response as needed
            return RedirectToAction("Index");
        }

        public IActionResult Download(string[] fileNames)
        {
            var memoryStream = new MemoryStream();

            using (var archive = new ZipArchive(memoryStream, ZipArchiveMode.Create, true))
            {
                foreach (var fileName in fileNames)
                {

                    string filePath = Path.Combine(Directory.GetCurrentDirectory(), "Uploads", fileName);
                    var entry = archive.CreateEntry(Path.GetFileName(filePath));

                    using (var entryStream = entry.Open())
                    using (var fileStream = new FileStream(filePath, FileMode.Open))
                    {
                        fileStream.CopyTo(entryStream);
                    }
                }
            }

            memoryStream.Position = 0;
            return File(memoryStream, "application/zip", $"Documents_{DateTime.Now:yyyyMMddHHmmss}.zip");
        }


        private List<Document> GetDocuments()
        {
            long? UserId = Convert.ToInt64(HttpContext.Session.GetString("User_Id")); 
            var directory = Path.Combine(Directory.GetCurrentDirectory(), "Uploads");
            //var fileNames = Directory.GetFiles(directory).Select(Path.GetFileName).ToList();

            var Document = _context.Document.Where(c=> c.User_Id == UserId).Distinct().ToList();
            //return Document;
            

            return Document;    
        }
        
        private void SaveDocumentToDatabase(string fileName, string filePath,long? UserId)
        {
            // Assuming you're using Entity Framework or another ORM for database operations
            // Replace this with the actual code to save data to your database

            var document = new Document
            {
                FileName = fileName,
                FilePath = filePath,
                UploadDate = DateTime.Now.Date,
                User_Id = UserId
            };
            _context.Add(document);
            _context.SaveChanges();
        }
    }
}

Views/Shared/_Layout.cshtml
@{
    string authToken = Context.Request.Cookies["AuthToken"];
    string username = Context.Request.Cookies["Username"];
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DocManager</title>
<link href="https://fonts.googleapis.com/" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/project1.styles.css" asp-append-version="true" />
</head>
<body>
                  
    <header>
        @if (!string.IsNullOrEmpty(username))
        {
        <nav class="navbar navbar-expand-lg bg-white" data-bs-theme="light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">DocuManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Dashboard" asp-action="Index">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Features</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="About" asp-action="AboutUs">About</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                    <div id="Box" >

                            <span id="username" style="  border-block-end-style:groove;color:black;">Welcome, @username!!</span>
                            <br />
                            <a class="btn btn-danger" asp-action="Logout" asp-controller="Authentication">Log Out</a>
                        
                    </div>
                </div>
            </div>
        </nav>
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DocManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>